### ISSUE TITLE
Syntax error, incorrect syntax near 'DISTINCT'.

### ISSUE THREAD

**Issue by thomaslevesque** [Azure/azure-cosmos-dotnet-v2#536]
I get this error for the following query:

```sql
SELECT DISTINCT VALUE c
FROM c
JOIN i in c.ExternalIdentities
where c._documentType = 'user' and i.ProviderName = @provider and i.ProviderSubjectId = @providerSubjectId
```

This looks like a server-generated error, but there are several suspicious things:
- I can't see the request going out using Fiddler (while I can see another very similar query that runs successfully); it looks like the error is thrown by the client, before even sending the query to the server.
- The same query works fine in Azure Storage Explorer or Azure Portal Data Explorer (replacing the parameters with literal values)
- The `InnerException` is a `COMException` (HRESULT: 0x800A0B00), which doesn't look like something I would see for an actual server-side error

What could cause that query to fail? Does `Microsoft.Azure.DocumentDB.Core` perform any SQL validation before sending the query?

Here's the full details of the exception:

```
Microsoft.Azure.Documents.BadRequestException
  HResult=0x80131500
  Message=Message: {"errors":[{"severity":"Error","location":{"start":9,"end":17},"code":"SC1001","message":"Syntax error, incorrect syntax near 'DISTINCT'."}]}
  Source=Microsoft.Azure.DocumentDB.Core
  StackTrace:
   at Microsoft.Azure.Documents.Query.QueryPartitionProvider.GetPartitionedQueryExecutionInfoInternal(SqlQuerySpec querySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, Boolean isContinuationExpected)
   at Microsoft.Azure.Documents.Query.QueryPartitionProvider.GetPartitionedQueryExecutionInfo(SqlQuerySpec querySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, Boolean isContinuationExpected)
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.<GetPartitionedQueryExecutionInfoAsync>d__41.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextFactory.<CreateDocumentQueryExecutionContextAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.<CreateDocumentQueryExecutionContextAsync>d__34.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.<ExecuteNextPrivateAsync>d__36`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at [REDACTED]
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at [REDACTED]
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at [REDACTED]

Inner Exception 1:
COMException: Exception from HRESULT: 0x800A0B00
```

**Comment by moderakh** [comment]
@thomaslevesque  can you please provide the following:

Which version of SDK are you using?
Version of .Net and if that's Standard or .Net Core
OS Platform (and 32 or 64 bit)
Does this query work if you replace the parameters with their values and pass the result string to the SDK?
Can you also please share the few lines repro code?

**Comment by thomaslevesque** [comment]
> Which version of SDK are you using?

Microsoft.Azure.DocumentDB.Core 1.9.1

> Version of .Net and if that's Standard or .Net Core

.NET Core 2.1. **Note: when I switch to .NET Framework 4.6.1, the same code works.**

> OS Platform (and 32 or 64 bit)

Windows 10 x64

> Does this query work if you replace the parameters with their values and pass the result string to the SDK?

No, same error

> Can you also please share the few lines repro code?

Here's a full repro: https://github.com/thomaslevesque/TestCosmosDistinctBug

**Comment by thomaslevesque** [comment]
I capture Fiddler traces with the `netcoreapp2.1` version:
https://gist.github.com/thomaslevesque/69d21c4ef132afda99d9d26f61f132c7

And with the `net461` version:
https://gist.github.com/thomaslevesque/43a064e1b903b78bf31631d0b393e65a

As you can see, with `netcoreapp2.1`, the query isn't even sent to the server, so the so-called syntax error is generated by the SDK itself (the fact that the exception is a `BadRequestException` and contains response headers is rather confusing).

**Comment by skram-softheme** [comment]
Hm, according to documentation DISTINC is not supported, am I missing something here?
https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sql-query#Aggregates https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sql-query-reference

**Comment by thomaslevesque** [comment]
@skram-softheme apparently it's not documented, but it works (except with .NET Core)... looks like the docs are out of date.

**Comment by crhistianramirez** [comment]
Can confirm this issue is resolved. I had noticed I was an an old 1.x version, upgrading to most recent (2.2.2 at the time of writing) worked
