### ISSUE TITLE
Count query: The size of the response exceeded the maximum allowed size

### ISSUE THREAD

**Issue by fredrik-annytab** [Azure/azure-cosmos-dotnet-v2#551]
Hi!

I am using Microsoft.Azure.DocumentDB.Core 1.9.1 and ASP.NET Core 2.1. 

MaxDegreeOfParallelism: 100,
MaxBufferedItemCount: 1000
MaxItemCount: 1

**Methods**
<pre>/// &#x3C;summary&#x3E;
        /// Get the count of active posts
        /// &#x3C;/summary&#x3E;
        public async Task&#x3C;ModelItem&#x3C;Int64&#x3E;&#x3E; GetActiveCount(string category_id)
        {
            // Create the sql string
            string sql = $&#x22;SELECT VALUE COUNT(1) FROM p JOIN c IN p.categories &#x22; 
                + $&#x22;WHERE p.model_type = @model_type AND p.inactive = @inactive AND c = @category_id&#x22;;

            // Create parameters
            SqlParameterCollection parameters = new SqlParameterCollection()
            {
                new SqlParameter(&#x22;@model_type&#x22;, &#x22;place&#x22;),
                new SqlParameter(&#x22;@inactive&#x22;, false),
                new SqlParameter(&#x22;@category_id&#x22;, category_id)
            };

            // Return the post
            return await this.cosmos_database_repository.GetByQuery&#x3C;Int64&#x3E;(sql, parameters);

        } // End of the GetActiveCount method</pre>

<pre>/// &#x3C;summary&#x3E;
        /// Get a document by a query
        /// &#x3C;/summary&#x3E;
        public async Task&#x3C;ModelItem&#x3C;T&#x3E;&#x3E; GetByQuery&#x3C;T&#x3E;(string sql, SqlParameterCollection parameters)
        {
            // Create variables to return
            ModelItem&#x3C;T&#x3E; model = new ModelItem&#x3C;T&#x3E;();

            // Set query options
            FeedOptions queryOptions = new FeedOptions { EnableCrossPartitionQuery = true, MaxDegreeOfParallelism = this.options.MaxDegreeOfParallelism, MaxBufferedItemCount = this.options.MaxBufferedItemCount, MaxItemCount = 1 };

            try
            {
                // Create a query
                IDocumentQuery&#x3C;T&#x3E; query = this.client.CreateDocumentQuery&#x3C;T&#x3E;(UriFactory.CreateDocumentCollectionUri(this.options.Database, this.options.Collection),
                    new SqlQuerySpec
                    {
                        QueryText = sql,
                        Parameters = parameters

                    }, queryOptions).AsDocumentQuery();

                // Get the response
                FeedResponse&#x3C;T&#x3E; response = await query.ExecuteNextAsync&#x3C;T&#x3E;();

                // Get the post
                foreach (T item in response)
                {
                    model.item = item;
                    break;
                }
            }
            catch (DocumentClientException de)
            {
                // Log the exception
                this.logger.LogError(de, $&#x22;GetByQuery&#x22;, null);
                model.error = true;
            }

            // Return the model
            return model;

        } // End of the GetByQuery method</pre>

**Exception**
2018-07-20T08:46:59.2561287+02:00  [ERR] GetByQuery (bdd7efef)
Microsoft.Azure.Documents.RequestEntityTooLargeException: Message: The size of the response exceeded the maximum allowed size, limit the  response size by specifying smaller value for 'x-ms-max-item-count' header.
ActivityId: 63d4188a-8a92-47a1-8ac2-5fba80bf417f, Request URI: /apps/03ef0ec0-72f1-480e-ac20-cfe12d9eecc5/services/60d14bfc-55f0-46d0-8018-23feac4c43ed/partitions/63deccc1-49a2-4d2e-a3f1-fc238cddb50a/replicas/131765395078189789s//dbs/production/colls/items/docs, RequestStats: , SDK: Windows/10.0.17134 documentdb-netcore-sdk/1.9.1
   at Microsoft.Azure.Documents.StoreReader.VerifyCanContinueOnException(DocumentClientException ex)
   at Microsoft.Azure.Documents.StoreReader.CreateStoreReadResult(StoreResponse storeResponse, Exception responseException, Boolean requiresValidLsn, Uri storePhysicalAddress)
   at Microsoft.Azure.Documents.StoreReader.ReadMultipleReplicasInternalAsync(DocumentServiceRequest entity, Boolean includePrimary, Int32 replicaCountToRead, Boolean requiresValidLsn, Boolean useSessionToken, Boolean checkMinLSN, Boolean forceReadAll)
   at Microsoft.Azure.Documents.StoreReader.ReadMultipleReplicaAsync(DocumentServiceRequest entity, Boolean includePrimary, Int32 replicaCountToRead, Boolean requiresValidLsn, Boolean useSessionToken, Boolean checkMinLSN, Boolean forceReadAll)
   at Microsoft.Azure.Documents.ConsistencyReader.ReadSessionAsync(DocumentServiceRequest entity)
   at Microsoft.Azure.Documents.ReplicatedResourceClient.InvokeAsync(DocumentServiceRequest request, TimeoutHelper timeout, Boolean isInRetry, Boolean forceRefresh)
   at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass18_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass2_0`1.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetry(Func`1 callbackMethod, Func`3 callShouldRetry, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetry(Func`1 callbackMethod, Func`3 callShouldRetry, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteAsync[TPolicyArg1](Func`2 callbackMethod, IRetryPolicy`1 retryPolicy, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.ReplicatedResourceClient.InvokeAsync(DocumentServiceRequest request, Func`2 prepareRequestAsyncDelegate)
   at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, Func`2 prepareRequestAsyncDelegate)
   at Microsoft.Azure.Documents.Client.DocumentClient.ExecuteQueryAsync(DocumentServiceRequest request)
   at Microsoft.Azure.Documents.Query.DocumentQueryClient.ExecuteQueryAsync(DocumentServiceRequest request)
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.ExecuteQueryRequestInternalAsync(DocumentServiceRequest request)
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.ExecuteQueryRequestAsync[T](DocumentServiceRequest request)
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.ExecuteRequestAsync[T](DocumentServiceRequest request)
   at Microsoft.Azure.Documents.Query.ParallelQuery.DocumentProducer`1.FetchAsync(IDocumentClientRetryPolicy retryPolicyInstance, CancellationToken token)
   at Microsoft.Azure.Documents.Query.ParallelQuery.DocumentProducer`1.FetchAsync(IDocumentClientRetryPolicy retryPolicyInstance, CancellationToken token)
   at Microsoft.Azure.Documents.Query.ParallelQuery.DocumentProducer`1.MoveNextAsync(CancellationToken token)
   at Microsoft.Azure.Documents.Query.ParallelDocumentQueryExecutionContextBase`1.TryMoveNextProducerAsync(DocumentProducer`1 producer, Func`2 producerRepairCallback, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.Query.ParallelDocumentQueryExecutionContext.DrainAsync(Int32 maxElements, CancellationToken token)
   at Microsoft.Azure.Documents.Query.ExecutionComponent.AggregateDocumentQueryExecutionComponent.DrainAsync(Int32 maxElements, CancellationToken token)
   at Microsoft.Azure.Documents.Query.PipelinedDocumentQueryExecutionContext.ExecuteNextAsync(CancellationToken token)
   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.ExecuteNextPrivateAsync[TResponse](CancellationToken token)
   at Myfavorite.Common.Repositories.CosmosDatabaseRepository.GetByQuery[T](String sql, SqlParameterCollection parameters) in D:\ASP-hemsidor\NetCoreApplications\Myfavorite\Myfavorite.Common\Repositories\CosmosDatabaseRepository.cs:line 309

**Comment by fredrik-annytab** [comment]
Hi, the problem seems to have disappeared since I changed the connection protocol. I was using: connectionPolicy.ConnectionMode = ConnectionMode.Direct;
connectionPolicy.ConnectionProtocol = Protocol.Https;

I changed  it to: connectionPolicy.ConnectionMode = ConnectionMode.Direct;
connectionPolicy.ConnectionProtocol = Protocol.Tcp;

**Comment by tjrobinson** [comment]
I get this error with a 64KB document even with `ConnectionMode.Direct` and `Protocol.Tcp`.
