### ISSUE TITLE
Method Not found bug is back (see #611)

### ISSUE THREAD

**Issue by xsgeek** [Azure/azure-cosmos-dotnet-v2#653]
this is the exact same issue as #611 but with 
- latest stable release of Microsoft.Azure.DocumentDB ver 2.2.1 
- latest stable release of Bulk Executer ver 1.4.0
- on .Net Framework 4.6.1 
  - no longer affecting just Core, project has no .Net Core targets or references.

**Workaround - Downgrade to Microsoft.Azure.DocumentDB ver 2.1.3**

---

IBulkExecutor bulkExecutor = new BulkExecutor(docClient, docCollection);
// Start the Bulk Executor
bulkExecutor.InitializeAsync().Wait();

Error Message:

Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Documents.Routing.CollectionRoutingMap> Microsoft.Azure.Documents.Routing.PartitionKeyRangeCache.TryLookupAsync(System.String, Microsoft.Azure.Documents.Routing.CollectionRoutingMap, System.Threading.CancellationToken)'.

Environment summary
SDK Version: Microsoft.Azure.CosmosDB.BulkExecutor.1.4.0
Microsoft.Azure.DocumentDB.2.1.3

OS Version: Windows 10 .64
Dot Net Framework: 4.6.1

**Comment by ealsur** [comment]
@xsgeek [BulkExecutor 1.4.0](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.BulkExecutor/1.4.0) has a hard dependency on SDK 2.1.3. 

![image](https://user-images.githubusercontent.com/1633401/50707756-d592bf80-1016-11e9-81b5-d4b1fb5100ca.png)


Using a higher version violates this contract. I tried to repro the ability to use a higher version in an empty Console Application but Nuget Restore blocks an attempt to restore a higher version of the SDK:

```
Attempting to gather dependency information for package 'Microsoft.Azure.DocumentDB.2.2.1' with respect to project 'ConsoleApp4', targeting '.NETFramework,Version=v4.5.1'
Gathering dependency information took 1.89 sec
Attempting to resolve dependencies for package 'Microsoft.Azure.DocumentDB.2.2.1' with DependencyBehavior 'Lowest'
Unable to resolve dependencies. 'Microsoft.Azure.DocumentDB 2.2.1' is not compatible with 'Microsoft.Azure.CosmosDB.BulkExecutor 1.4.0 constraint: Microsoft.Azure.DocumentDB (= 2.1.3)'.
```

This is an expected behavior if the Nuget requirements are not being honored as the contracts might differ.

**Comment by r3plica** [comment]
This is still happening to me https://stackoverflow.com/questions/54213795/azure-cosmos-bulkexecutermethod-not-found

**Comment by ealsur** [comment]
@r3plica Did you downgrade the package version by any chance? Can you try deleting your bin/obj folder or running a Clean on the project?

**Comment by topagarwal** [comment]
I am seeing the issue with following latest packages:

 ```
  <PackageReference Include="Microsoft.Azure.CosmosDB.BulkExecutor" Version="2.0.0-preview" />
    <PackageReference Include="Microsoft.Azure.DocumentDB" Version="2.13.1" />
    <PackageReference Include="Microsoft.Azure.DocumentDB.Core" Version="2.13.1" />
```

**Comment by ealsur** [comment]
@topagarwal Your mix of packages is kind of weird.

You would need either:

* Microsoft.Azure.DocumentDB 2.13.1 and Microsoft.Azure.CosmosDB.BulkExecutor 1.8.9 if the app is a full framework (net46/net47)
* Microsoft.Azure.DocumentDB.Core 2.13.1 and Microsoft.Azure.CosmosDB.BulkExecutor 2.5.1-preview if the app is a NET Core application

**Comment by topagarwal** [comment]
Thanks. I've netstandard2.0 library. I made the change you suggesting. Still seeing the issue.

Using this 
`<PackageReference Include="Microsoft.Azure.CosmosDB.BulkExecutor" Version="2.0.0-preview" />
  <PackageReference Include="Microsoft.Azure.DocumentDB.Core" Version="2.13.1" />`

`System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Documents.Routing.CollectionRoutingMap> Microsoft.Azure.Documents.Routing.PartitionKeyRangeCache.TryLookupAsync(System.String, Microsoft.Azure.Documents.Routing.CollectionRoutingMap, System.Threading.CancellationToken, Boolean)'.
  Source=Microsoft.Azure.CosmosDB.BulkExecutor
  StackTrace:
   at Microsoft.Azure.CosmosDB.BulkExecutor.BulkExecutor.<InitializeAsync>d__19.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.CosmosDB.BulkExecutor.BulkExecutor.InitializeAsync()
   at Microsoft.Azure.Sphere.Image.DataMigration.CosmosDataWriter..ctor(String connectionString, String databaseName, String collectionName, ILogger`1 logger) in C:\services\Image\Image.DataMigration\CosmosDataWriter.cs:line 81
   at Microsoft.Azure.Sphere.Image.Service.Startup.<>c__DisplayClass7_0.<ConfigureServices>b__4(IServiceProvider serviceProvider) in C:\services\Image\Image.Service\Startup.cs:line 217
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitNoCache(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHost.<StartAsync>d__27.MoveNext()
`

**Comment by topagarwal** [comment]
Thanks for the reply. Changing to 2.5.1-preview solved it for me.
