### ISSUE TITLE
Invalid Continuation Token: filter

### ISSUE THREAD

**Issue by fredrik-annytab** [Azure/azure-cosmos-dotnet-v2#657]
I get a list of items from document db and a continuation token, the continuation token is saved as a string and sent as a parameter to get the next page. When I try to get the third page I get DocumentClientException: Invalid Continuation Token. Problems is observed in Microsoft.Azure.DocumentDB.Core v2.2.0 and in Microsoft.Azure.DocumentDB.Core v2.2.1.

The token that failed looks like this: "[{\"compositeToken\":{\"token\":\"+RID:oMkZAP6gXQAFAAAAAAAAAA==#RT:2#TRC:20#RTD:yBpkb3hAYW5ueXRhYi5zZQ==#FPC:AgEAAAAQAAfAYAEEARDYjQsT8Hu9/wM=\",\"range\":{\"min\":\"\",\"max\":\"FF\"}},\"orderByItems\":[{\"item\":\"dox@annytab.se\"}],\"rid\":\"oMkZAP6gXQAFAAAAAAAAAA==\",\"skipCount\":0,\"filter\":\"m.email >= \"email@gmail.com \"\"}]"

Items is sorted by email and the email in the filter parameter includes a space and is surrounded by  \" ( \"email@gmail.com \"). In version 2.1.3 filter is \"true\" instead.

**To Reproduce**
<pre>public async Task&lt;ModelPage&lt;T&gt;&gt; GetListByQuery&lt;T&gt;(string sql, SqlParameterCollection parameters, Int32 page_size, string ct)
{
	// Create variables to return
	ModelPage&lt;T&gt; page = new ModelPage&lt;T&gt;();

	// Set query options
	FeedOptions queryOptions = new FeedOptions { EnableCrossPartitionQuery = true, MaxDegreeOfParallelism = this.options.MaxDegreeOfParallelism, MaxBufferedItemCount = this.options.MaxBufferedItemCount, MaxItemCount = page_size, RequestContinuation = ct };

	try
	{
		// Create the query
		IDocumentQuery&lt;T&gt; query = this.client.CreateDocumentQuery&lt;T&gt;(UriFactory.CreateDocumentCollectionUri(this.options.Database, this.options.Collection),
			new SqlQuerySpec
			{
				QueryText = sql,
				Parameters = parameters

			}, queryOptions).AsDocumentQuery();

		// Get the response
		FeedResponse&lt;T&gt; response = await query.ExecuteNextAsync&lt;T&gt;();

		// Get the continuation token
		page.ct = response.ResponseContinuation;

		// Get posts
		page.items = response.ToList&lt;T&gt;();
	}
	catch (DocumentClientException de)
	{
		// Log the exception
		this.logger.LogError(de, $"GetListByQuery", null);
		page.error = true;
	}

	// Return the page
	return page;

} // End of the GetListByQuery method</pre>

**Expected behavior**
I expect to be able to iterate all items page by page until I have reached the end of the list.

**Actual behavior**
I get a DocumentClientException (Invalid Continuation Token) and no items returned on the third page.

Microsoft.Azure.Documents.DocumentClientException: Invalid Continuation Token
ActivityId: 9b338e69-4eb4-4cc0-9c7a-9059114a4bfe, Microsoft.Azure.Documents.Common/2.1.0.0, Windows/10.0.17134 documentdb-netcore-sdk/2.2.1
   at Microsoft.Azure.Documents.Client.ClientExtensions.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, Boolean throwOnKnownClientErrorCodes)
   at Microsoft.Azure.Documents.GatewayStoreModel.<>c__DisplayClass21_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass1_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteAsync(Func`1 callbackMethod, IRetryPolicy retryPolicy, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.GatewayStoreModel.InvokeAsync(DocumentServiceRequest request, ResourceType resourceType, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.Client.DocumentClient.ExecuteQueryAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.Query.DocumentQueryClient.ExecuteQueryAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.ExecuteQueryRequestInternalAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.ExecuteQueryRequestAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.ExecuteRequestAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.Query.DefaultDocumentQueryExecutionContext.ExecuteOnceAsync(IDocumentClientRetryPolicy retryPolicyInstance, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.Query.DefaultDocumentQueryExecutionContext.<>c__DisplayClass9_0.<<ExecuteInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass1_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteAsync(Func`1 callbackMethod, IRetryPolicy retryPolicy, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.Query.DefaultDocumentQueryExecutionContext.ExecuteInternalAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.ExecuteNextAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.Query.ProxyDocumentQueryExecutionContext.ExecuteNextAsync(CancellationToken token)
   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.ExecuteNextPrivateAsync[TResponse](CancellationToken cancellationToken)
   at Doxservr.Common.Repositories.CosmosDatabaseRepository.GetListByQuery[T](String sql, SqlParameterCollection parameters, Int32 page_size, String ct) in D:\ASP-hemsidor\NetCoreApplications\Doxservr\Doxservr.Common\Repositories\CosmosDatabaseRepository.cs:line 398

**Environment summary**
SDK Version: ASP.NET Core 2.2
OS Version: IIS 10 (Windows)

**Comment by fredrik-annytab** [comment]
I added the continuation token to a html page without encoding it. This problem can be solved with UrlEncode and UrlDecode.
