### ISSUE TITLE
DocumentClientException is not deserializable

### ISSUE THREAD

**Issue by WouterDemuynck** [Azure/azure-cosmos-dotnet-v2#691]
**Description**
I encountered an exception of type `DocumentClientException` while working with **ServiceFabric* actor remoting. However, instead of the underlying exception I get a deserialization exception on the remoting client because that exception type is not properly deserializable.

Exception message:
```
Failed to deserialize and get remote exception  System.Runtime.Serialization.SerializationException: The constructor with parameters (SerializationInfo, StreamingContext) is not found in ISerializable type 'Microsoft.Azure.Documents.DocumentClientException'.
```

For stack trace, see below.

**To Reproduce**
You can reproduce this exception by causing any `DocumentClientException` inside of a **ServiceFabric** actor and consuming the actor from a different application.

Alternatively, this error will also occur when directly deserializing a `DocumentClientException` using the classes in `System.Runtime.Serialization`.

**Expected behavior**
The `DocumentClientException` should be properly deserialized and received on the consumer code of the **ServiceFabric** actor.

**Actual behavior**
An exception stating that the `DocumentClientException` could not be deserialized.

**Environment summary**
SDK Version: 2.2

**Additional context**
Stack trace of the exception:
```
Failed to deserialize and get remote exception  System.Runtime.Serialization.SerializationException: The constructor with parameters (SerializationInfo, StreamingContext) is not found in ISerializable type 'Microsoft.Azure.Documents.DocumentClientException'.
   at System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.GetISerializableConstructor()
   at System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadISerializable(ClassDataContract classContract)
   at System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateClassReader(ClassDataContract classContract)
   at System.Runtime.Serialization.XmlFormatReaderGenerator.GenerateClassReader(ClassDataContract classContract)
   at System.Runtime.Serialization.ClassDataContract.get_XmlFormatReaderDelegate()
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeInSharedTypeMode(XmlReaderDelegator xmlReader, Int32 declaredTypeID, Type declaredType, String name, String ns)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, String name, String ns)
   at System.Runtime.Serialization.NetDataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
   at Microsoft.ServiceFabric.Services.Remoting.V1.RemoteExceptionInformation.TryDeserializeException(Byte[] data, Exception& result)
```

I believe the only thing that needs to happen here is to implement a proper constructor with the `SerializationInfo` and `StreamingContext` signature directly on the class.

```csharp
protected DocumentClientException(SerializationInfo info, StreamingContext context)
{
  // TODO
}
```

See also: [Implement serialization constructors](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2229-implement-serialization-constructors?view=vs-2019)

**Comment by YvesRoyer** [comment]
Any news on this exception sinec the thread is still open? We also encountered this exception for quite some time.
