### ISSUE TITLE
Exception on OrderByQueryResult with message "Value cannot be null. Parameter name: rid can not be null or empty." when query contain ORDER BY with ALIAS

### ISSUE THREAD

**Issue by stringformat** [Azure/azure-cosmos-dotnet-v2#717]
**Describe the bug**
Exception throw when use ORDER BY with an ALIAS like
"SELECT d.Id, d.Name FROM c.Document AS d ORDER BY d.Date DESC" 

To avoid this, i had to remove this alias.

Microsoft Azure Cosmos Emulator 2.2.1.0 (2b4af9b3)
SDK Version: 2.4.0
OS Version : Windows 10 1809

**Additional context**
Value cannot be null. Parameter name: rid can not be null or empty.
   at Microsoft.Azure.Documents.Query.OrderByQueryResult..ctor(String rid, QueryItem[] orderByItems, Object payload)
   at lambda_method(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2031
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 476
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 167
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 907
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 873
   at Microsoft.Azure.Documents.DocumentServiceResponse.GetEnumerable[T](Type resourceType, Func`2 callback)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.Azure.Documents.DocumentServiceResponse.GetQueryResponse[T](Type resourceType, Boolean lazy, Int32& itemCount)
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.GetFeedResponse[T](DocumentServiceResponse response)
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.ExecuteQueryRequestAsync[T](DocumentServiceRequest request, IDocumentClientRetryPolicy retryPolicyInstance, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.Query.DocumentProducer`1.BufferMoreDocuments(CancellationToken token)
   at Microsoft.Azure.Documents.Query.DocumentProducer`1.<>c.<MoveNextPage>b__62_1(ExceptionDispatchInfo exceptionDispatchInfo)
   at Microsoft.Azure.Documents.Query.DocumentProducer`1.MoveNextPage(CancellationToken token)
   at Microsoft.Azure.Documents.Query.DocumentProducer`1.MoveNextAsyncImplementation(CancellationToken token)
   at Microsoft.Azure.Documents.Query.DocumentProducer`1.MoveNextAsync(CancellationToken token)
   at Microsoft.Azure.Documents.Query.DocumentProducerTree`1.MoveNextAsyncImplementation(CancellationToken token)
   at Microsoft.Azure.Documents.Query.DocumentProducerTree`1.ExecuteWithSplitProofing(Func`2 function, Boolean functionNeedsBeReexecuted, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.Query.DocumentProducerTree`1.MoveNextIfNotSplit(CancellationToken token)
   at Microsoft.Azure.Documents.Query.CrossPartitionQueryExecutionContext`1.InitializeAsync(String collectionRid, IReadOnlyList`1 partitionKeyRanges, Int32 initialPageSize, SqlQuerySpec querySpecForInit, Dictionary`2 targetRangeToContinuationMap, Boolean deferFirstPage, String filter, Func`2 filterCallback, CancellationToken token)
   at Microsoft.Azure.Documents.Query.OrderByDocumentQueryExecutionContext.InitializeAsync(String requestContinuation, String collectionRid, List`1 partitionKeyRanges, Int32 initialPageSize, SortOrder[] sortOrders, String[] orderByExpressions, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.Query.OrderByDocumentQueryExecutionContext.CreateAsync(InitParams constructorParams, CrossPartitionInitParams initParams, CancellationToken token)
   at Microsoft.Azure.Documents.Query.PipelinedDocumentQueryExecutionContext.<>c__DisplayClass5_0.<<CreateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Documents.Query.ExecutionComponent.DistinctDocumentQueryExecutionComponent.CreateAsync(String requestContinuation, Func`2 createSourceCallback, DistinctQueryType distinctQueryType)
   at Microsoft.Azure.Documents.Query.PipelinedDocumentQueryExecutionContext.<>c__DisplayClass5_2.<<CreateAsync>b__3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Documents.Query.PipelinedDocumentQueryExecutionContext.CreateAsync(InitParams constructorParams, String collectionRid, PartitionedQueryExecutionInfo partitionedQueryExecutionInfo, List`1 partitionKeyRanges, Int32 initialPageSize, String requestContinuation, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.Query.ProxyDocumentQueryExecutionContext.ExecuteNextAsync(CancellationToken token)
   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.ExecuteNextPrivateAsync[TResponse](CancellationToken cancellationToken)

**Comment by kirankumarkolli** [comment]
@bchong95 can u please look into it?
