### ISSUE TITLE
Receiving ServiceUnavailableException (which is an internal class)

### ISSUE THREAD

**Issue by rodrigovaras** [Azure/azure-cosmos-dotnet-v2#732]
Our code attempt to find an existing document using this:
            try
            {
                var documentUri = UriFactory.CreateDocumentUri(DatabaseId, ContactDataCollectionId, contactId);
                var response = await Client.ReadDocumentAsync<ContactDataDocument>(documentUri, cancellationToken: cancellationToken);
                return (response.Document, response.RequestLatency);
            }
            catch (DocumentClientException e) when (e.StatusCode == HttpStatusCode.NotFound)
            {
                return (null, TimeSpan.FromMilliseconds(0));
            }

I would expect most of the errors (event not found) be reported as a DocumentClientExeption instead of a private type from the SDK.

But the callstack i'm seeing:

[ServiceUnavailableException]: Service is currently unavailable.
ActivityId: 04054dfb-9b7d-4e11-a68b-35f45bb708cb, Linux/3.9.2 documentdb-netcore-sdk/2.0.0
[GoneException]: The requested resource is no longer available at the server.
ActivityId: 04054dfb-9b7d-4e11-a68b-35f45bb708cb, Linux/3.9.2 documentdb-netcore-sdk/2.0.0
--- Stack Trace ---
Microsoft.Azure.Documents.ServiceUnavailableException: Service is currently unavailable.
ActivityId: 04054dfb-9b7d-4e11-a68b-35f45bb708cb, Linux/3.9.2 documentdb-netcore-sdk/2.0.0 ---> Microsoft.Azure.Documents.GoneException: The requested resource is no longer available at the server.
ActivityId: 04054dfb-9b7d-4e11-a68b-35f45bb708cb, Linux/3.9.2 documentdb-netcore-sdk/2.0.0
 at Microsoft.Azure.Documents.TimeoutHelper.ThrowGoneIfElapsed()
 at Microsoft.Azure.Documents.StoreReader.ReadMultipleReplicasInternalAsync(DocumentServiceRequest entity, Boolean includePrimary, Int32 replicaCountToRead, Boolean requiresValidLsn, Boolean useSessionToken, ReadMode readMode, Boolean checkMinLSN, Boolean forceReadAll)
 at Microsoft.Azure.Documents.StoreReader.ReadMultipleReplicaAsync(DocumentServiceRequest entity, Boolean includePrimary, Int32 replicaCountToRead, Boolean requiresValidLsn, Boolean useSessionToken, ReadMode readMode, Boolean checkMinLSN, Boolean forceReadAll)
 at Microsoft.Azure.Documents.ConsistencyReader.ReadSessionAsync(DocumentServiceRequest entity, ReadMode readMode)
 at Microsoft.Azure.Documents.ReplicatedResourceClient.InvokeAsync(DocumentServiceRequest request, TimeoutHelper timeout, Boolean isInRetry, Boolean forceRefresh)
 at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass21_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass4_0`1.<<ExecuteAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetry(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
 --- End of inner exception stack trace ---
 at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
 at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetry(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
 at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteAsync[TPolicyArg1](Func`2 callbackMethod, IRetryPolicy`1 retryPolicy, Func`2 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
 at Microsoft.Azure.Documents.ReplicatedResourceClient.InvokeAsync(DocumentServiceRequest request, Func`2 prepareRequestAsyncDelegate, CancellationToken cancellationToken)
 at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, Func`2 prepareRequestAsyncDelegate)
 at Microsoft.Azure.Documents.Client.DocumentClient.ReadAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
 at Microsoft.Azure.Documents.Client.DocumentClient.ReadDocumentPrivateAsync[T](String documentLink, RequestOptions options, IDocumentClientRetryPolicy retryPolicyInstance, CancellationToken cancellationToken)
 at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass1_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetry(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
 at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
 at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetry(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
 at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteAsync(Func`1 callbackMethod, IRetryPolicy retryPolicy, CancellationToken cancellationToken, Action`1 preRetryCallback)
 at Microsoft.VsCloudKernel.SignalService.DatabaseBackplaneProvider.GetContactDataDocumentAsync(String contactId, CancellationToken cancellationToken) in S:\src\services\containers\VsClk.SignalService\BackplaneProviders\DatabaseBackplaneProvider\DatabaseBackplaneProvider.cs:line 317
 at Microsoft.VsCloudKernel.SignalService.DatabaseBackplaneProvider.UpdateContactAsync(ContactDataChanged`1 contactDataChanged, CancellationToken cancellationToken) in S:\src\services\containers\VsClk.SignalService\BackplaneProviders\DatabaseBackplaneProvider\DatabaseBackplaneProvider.cs:line 192
 at Microsoft.VsCloudKernel.SignalService.PresenceService.OnContactChangedAsync(Object sender, ContactChangedEventArgs e) in S:\src\services\containers\VsClk.SignalService\PresenceServiceHub\PresenceService.cs:line 558

SDK Version: 2.0.0
OS Version (e.g. Windows, Linux, MacOSX):  Linux

**Comment by j82w** [comment]
@rodrigovaras what .NET version are you using?

**Comment by kirankumarkolli** [comment]
Sample code above is only NotFound exceptions only. Others are still thrown out. 

```csharp
catch (DocumentClientException e) when (**e.StatusCode == HttpStatusCode.NotFound**)
```

ServiceUnavailableException is also a DocumentClientException as defined below. 
Unconditional catch will handle all such.

```csharp
    internal sealed class ServiceUnavailableException : DocumentClientException
```
