### ISSUE TITLE
Null exception using GROUP BY: orderedAliases

### ISSUE THREAD

**Issue by stzhmsfttest** [Azure/azure-cosmos-dotnet-v2#753]
**Describe the bug**
message: "Value cannot be null. Parameter name: orderedAliases"

stackTrace: "   at Microsoft.Azure.Documents.Query.ExecutionComponent.GroupByDocumentQueryExecutionComponent..ctor(IReadOnlyDictionary`2 groupByAliasToAggregateType, IReadOnlyList`1 orderedAliases, Boolean hasSelectValue, IDocumentQueryExecutionComponent source)
↵   at Microsoft.Azure.Documents.Query.ExecutionComponent.GroupByDocumentQueryExecutionComponent.<CreateAsync>d__14.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at Microsoft.Azure.Documents.Query.PipelinedDocumentQueryExecutionContext.<>c__DisplayClass5_3.<<CreateAsync>b__4>d.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at Microsoft.Azure.Documents.Query.PipelinedDocumentQueryExecutionContext.<CreateAsync>d__5.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextFactory.<CreateDocumentQueryExecutionContextAsync>d__3.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.<ExecuteNextPrivateAsync>d__36`1.MoveNext()"

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Environment summary**

SDK Version:
OS Version (e.g. Windows, Linux, MacOSX): 

**Additional context**

**Comment by stzhmsfttest** [comment]
our Microsoft.Azure.Documents.ServiceInterop.dll has signing time of 
‎Thursday, ‎November ‎14, ‎2019 5:07:39 PM
which should be the one from nuget package

**Comment by j82w** [comment]
1. Is the running against an emulator? Is it the latest emulator?
2. Is the application x64?

**Comment by stzhmsfttest** [comment]
The application is x64
It's running against the docker emulator
microsoft/azure-cosmosdb-emulator                          latest              d2670c3db14c        3 weeks ago         11.8GB
I don't know how to check the version of the docker one since it doesn't show up in the UI
