### ISSUE TITLE
Azure DevOps - running tests against Cosmos DB Emulator throws "Resource Not Found" when creating Collection if to many tests

### ISSUE THREAD

**Issue by tank104** [Azure/azure-cosmos-dotnet-v2#795]
**Describe the bug**
With one project we have lots of Cosmos DB tests - each which creates a collection to run the tests in.  The tests are all in one class so should be running in parallel.
There are probably around 20 tests.  If I comment a few out (doesn't matter which), it fixes it.

**To Reproduce**

Create a test class with 25 tests that create a database and collection.  Run it on Azure Dev Ops "windows-2019" agent, with a step that runs .Net Core "Test"

**Expected behavior**
Tests all run fine

**Actual behavior**
One test will crash with error:
oft.Azure.Documents.DocumentClientException : Message: {"Errors":["Resource Not Found"]}
ActivityId: 42ce4dd1-5364-4f4c-a8cf-0a4854130fc6, Request URI: /apps/DocDbApp/services/DocDbServer15/partitions/a4cb495b-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats:
RequestStartTime: 2020-07-02T22:44:55.3842510Z, RequestEndTime: 2020-07-02T22:44:58.1115917Z, Number of regions attempted:1
ResponseTime: 2020-07-02T22:44:56.9968919Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer15/partitions/a4cb495b-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 1, GlobalCommittedLsn: -1, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 449, SubStatusCode: 0, RequestCharge: 0, ItemLSN: -1, SessionToken: , UsingLocalLSN: False, TransportException: null, ResourceType: BatchApply, OperationType: BatchApply
ResponseTime: 2020-07-02T22:44:57.0438909Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer15/partitions/a4cb495b-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 1, GlobalCommittedLsn: -1, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 449, SubStatusCode: 0, RequestCharge: 0, ItemLSN: -1, SessionToken: , UsingLocalLSN: False, TransportException: null, ResourceType: BatchApply, OperationType: BatchApply
ResponseTime: 2020-07-02T22:44:58.1115917Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10253/apps/DocDbApp/services/DocDbServer15/partitions/a4cb495b-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 1, GlobalCommittedLsn: -1, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 45.38, ItemLSN: -1, SessionToken: -1#1, UsingLocalLSN: False, TransportException: null, ResourceType: BatchApply, OperationType: BatchApply
, SDK: Microsoft.Azure.Documents.Common/2.11.0, Windows/10.0.17763 documentdb-netcore-sdk/2.2.2

And stackflow:
at Microsoft.Azure.Documents.Client.ClientExtensions.ParseResponseAsync(HttpResponseMessage responseMessage, JsonSerializerSettings serializerSettings, Boolean throwOnKnownClientErrorCodes)
at Microsoft.Azure.Documents.GatewayStoreModel.<>c__DisplayClass20_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass1_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteAsync(Func`1 callbackMethod, IRetryPolicy retryPolicy, CancellationToken cancellationToken, Action`1 preRetryCallback)
at Microsoft.Azure.Documents.GatewayStoreModel.InvokeAsync(DocumentServiceRequest request, ResourceType resourceType, CancellationToken cancellationToken)
at Microsoft.Azure.Documents.GatewayStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
at Microsoft.Azure.Documents.Client.DocumentClient.CreateAsync(DocumentServiceRequest request, CancellationToken cancellationToken)
at Microsoft.Azure.Documents.Client.DocumentClient.CreateDocumentCollectionPrivateAsync(String databaseLink, DocumentCollection documentCollection, RequestOptions options, IDocumentClientRetryPolicy retryPolicyInstance)
at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass1_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteAsync(Func`1 callbackMethod, IRetryPolicy retryPolicy, CancellationToken cancellationToken, Action`1 preRetryCallback)
at Microsoft.Azure.Documents.Client.DocumentClient.CreateDocumentCollectionIfNotExistsPrivateAsync(String databaseLink, DocumentCollection documentCollection, RequestOptions options)

**Environment summary**

SDK Version: Microsoft.Azure.DocumentDB.Core 2.2.2
OS Version Window

**Additional context**
It seems to be related to the amount of collections created (not databases) as I tried doing one database with all collections and it still didn't work.  Each test also cleans up the collection and database and deletes it.
Is there some limit thats being hit?

Locally it works fine against the emulator.

**Comment by colgreen** [comment]
Hello. Did you learn anything more about this problem? I would guess that it may be a limitation of CosmosDB Emulator.

**Comment by tank104** [comment]
It went away for us, are you getting it?

**Comment by robjackstewart** [comment]
Hey all, I hit this problem in the v3 client, so unsure if this applies to v2, however, it was to do with the lifetime scope of the `CosmosClient`. We had it registered as a singleton, however, if you recreate a container with the same name without recreating the client, then it occasionally throws this exception. The reason is because the client caches the unique identifiers of the partition keys, so when it tries to find those partition keys upon your next query, it throws a 404, because that partition does not exist. It will refresh the cache of the partition keys, but does not retry because the client has no idea what your intentions are, so then moving it to either `Scoped` or `Transient` removed the problem for us.
